CREATE TABLE [dbo].[Client]
(
	ClientId INT IDENTITY,
	Lastname VARCHAR(50) NOT NULL,
	Firstname VARCHAR(50) NOT NULL,
	Company VARCHAR(50) NOT NULL,
	Phone VARCHAR(50) NOT NULL,
	Email VARCHAR(150) UNIQUE NOT NULL,
	Passwd VARBINARY(64) NOT NULL
	CONSTRAINT PK_ClientID PRIMARY KEY (ClientId)
)
