CREATE TABLE [dbo].[Dev]
(
	DevId INT IDENTITY,
	Lastname VARCHAR(50) NOT NULL,
	Firstname VARCHAR(50) NOT NULL,
	BirthDate DATETIME2(0) NOT NULL,
	[Phone] VARCHAR(50) NOT NULL,
	Email VARCHAR(150) UNIQUE NOT NULL,
	Passwd VARBINARY(64) NOT NULL,
	CONSTRAINT PK_DevID PRIMARY KEY (DevId)
)
